# Generated by Django 4.2.6 on 2023-10-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='picture',
        ),
        migrations.AddField(
            model_name='turf',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='turf_images/'),
        ),
        migrations.AlterField(
            model_name='turf',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='turf',
            name='time_slots',
            field=models.CharField(max_length=100),
        ),
    ]
