# Generated by Django 4.2.6 on 2023-10-28 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0002_remove_turf_picture_turf_image_alter_turf_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='time_slots',
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=100)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfs.turf')),
            ],
        ),
    ]
