# Generated by Django 4.2.6 on 2023-10-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0004_remove_timeslot_slot_timeslot_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='connect',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='turf',
            name='facilities',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='turf',
            name='info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='turf',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turf',
            name='schedule',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
