# Generated by Django 4.2.6 on 2023-10-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0013_booking_turf_owner_email_booking_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='owner_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
