# Generated by Django 4.2.6 on 2023-10-28 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_turf_connect_turf_facilities_turf_info_turf_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.timeslot')),
            ],
        ),
    ]
