# Generated by Django 4.2.6 on 2023-10-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_turf_schedule_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
