# Generated by Django 4.2.6 on 2023-10-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_turf_facilities_remove_turf_sports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='turf_owner_email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='turf',
            name='owner_email',
            field=models.EmailField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
